number: '١٢٣٤٥٦٧٨٩٠'
symbol: '.'
lang_char: "!#$%&'(+,/:@ءآأؤإئابةتثجحخدذرزسشصضطظعغفقكلمنهوىيًٌٍَُِّْٰٓٔٱٹپچڈڑژکڭگںھۀہۂۃۆۇۈۋیېےۓەﻓﮮﺨﻏﻊﺜﺒﺑﻗﻭﺓﻣﻟﺺﺁﺣﮉﻱﮬﺎﺶﺦﺐﺡﻚﺅﺹﺾﺟﻘﻢﮑﻬﻒﻆﺚﺯﺱﻡﻷﭘﺞﻋﺖﺊﻠﻶﮩﺌﺼﻝﺥﮧﺿﻖﻐﻸﻩ؟ﻻﻤﻎﺳﯩﻼﺽﮨﺮﻲﺕﻙﻑﺠﻺﺂﻫﻪﭗﺪﻮﺩﺰﺛﮭﭽﺈﻰﷲﻜﻨﮔﻁﭖﻛﺷﺏﻞ،ﺋﮫﻈﻂﺗﺃﮪﺄﻍﮦﻵﻧﻳﻹﺬﺝﻦﺴﺵﭙﺧﺫﺆﺍﯨﻅﺔﺀﭻـﻕﻀﻄﺇﺸﻔﭺﺲﻉﭼ؛ﺤﺘﺙﻯﻃﻥﺉﺻﻌﺢﻇﮐﻴﺭﮎﮕﮏﮊﮯ"
experiment_name: 'ar_ocr'
train_data: 'all_data/ar_train_filtered'
valid_data: 'all_data/ar_val'
manualSeed: 1111
# workers: 6
workers: 32
batch_size: 256 # 128 #32
num_iter: 300000
valInterval: 17000
saved_model: ''
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'ar_train_filtered' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 50 
imgH: 64
imgW: 320 # 620
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False